### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by Trbb** [Mcracker/EWBF-dev-fee-to-myWallet#8]
Hi , now this script is working on my rig , and pretty good.

but i have a question, i m mining on nanopool, and i want to set Minimum payout ,

so i need set a e-mail per worker. how to add email in server.js?  :(

sorry my english not good:(

**Comment by Jaywizkid** [comment]
Just make the worker name in server.js the same as it is for your miner config.  This way the pool just sees both the DevFee miner and the real miner as one.  Use the email from the miner config to login like you normally would.  This is how I have done it on flypool and it works fine.

**Comment by Trbb** [comment]
cause flypool set Minimum payout is use IP to set. 
but nanopool is use e-mail to set :(

**Comment by Jaywizkid** [comment]
I don't see how that makes a difference..Just make the worker name the same in server.js as it is in your miner config, this way the pool sees both workers as the same worker.

**Comment by Trbb** [comment]
ooooooh, thanks again  :)
